var json = [
  {
    sitesName: '综合', icon: 'Monitor', sites: [
      { sName: '百度', sUrl: 'https://www.baidu.com', sImg: 'https://dgss0.bdstatic.com/5bVWsj_p_tVS5dKfpU_Y_D3/res/r/image/2021-3-5/baidulogo.png', sInfo: '信息', sLevel: 4 },
      { sName: '头条', sUrl: 'https://www.toutiao.com/', sImg: 'https://sf3-cdn-tos.douyinstatic.com/obj/eden-cn/uhbfnupkbps/toutiao_favicon.ico', sInfo: '信息', sLevel: 4 },
      { sName: '新浪', sUrl: 'https://www.sina.com.cn/', sImg: 'https://dgss0.bdstatic.com/5bVWsj_p_tVS5dKfpU_Y_D3/qiusuo_icon/10597f220b047cee3e8ea50e91886d71.ico', sInfo: '信息' },
      { sName: '腾讯', sUrl: 'http://www.qq.com/', sImg: 'https://dgss2.bdstatic.com/5bVYsj_p_tVS5dKfpU_Y_D3/qiusuo_icon/5838ed1d6a3eef9f91341d9a8af16db8.ico', sInfo: '' },
      { sName: '凤凰网', sUrl: 'https://www.ifeng.com/', sImg: 'https://dgss0.bdstatic.com/5bVWsj_p_tVS5dKfpU_Y_D3/data/3321005414876972a6ccd92043996804', sInfo: '' },
      { sName: '中关村在线', sUrl: 'https://www.zol.com.cn/', sImg: 'https://icon.zol-img.com.cn/mainpage/2019logo/homeLogo-vre1x.png', sInfo: '' },
      { sName: 'IT之家', sUrl: 'https://www.ithome.com/', sImg: 'https://img.ithome.com/www/ithome.logo.svg', sInfo: '' },
      { sName: '携程网', sUrl: 'https://www.ctrip.com/', sImg: 'https://pic.c-ctrip.com/platform/online/login/c_logo2020.png', sInfo: '' },
      { sName: '12306', sUrl: 'https://www.12306.cn/index/', sImg: 'https://www.12306.cn/index/images/logo.jpg', sInfo: '' },
      { sName: '雪球', sUrl: 'https://xueqiu.com/', sImg: 'https://assets.imedao.com/images/favicon.png', sInfo: '' },
      { sName: '东方财富', sUrl: 'https://www.eastmoney.com/', sImg: 'https://g1.dfcfw.com/g3/201909/20190912110958.jpg', sInfo: '' },
      { sName: '思否', sUrl: 'https://segmentfault.com/', sImg: 'https://static.segmentfault.com/main_site_next/5a904b2b/_next/static/media/logo-b.1ef53c6e.svg', sInfo: '微信登录' },
      { sName: '今日头条号', sUrl: 'https://mp.toutiao.com/profile_v4/', sImg: '', sInfo: '手机号登录' },
      { sName: 'CSDN', sUrl: 'https://www.csdn.net/', sImg: 'https://img-home.csdnimg.cn/images/20201124032511.png', sInfo: '手机号登录' },
      { sName: '千图网', sUrl: 'https://www.58pic.com/', sImg: 'https://icon.qiantucdn.com/static/images/logo-new.png', sInfo: '手机号登录' },
      { sName: '简书', sUrl: 'https://www.jianshu.com', sImg: '', sInfo: '' },
      { sName: '126邮箱', sUrl: 'https://mail.126.com/', sImg: 'https://mimg.127.net/p/js6/lib/img/126logo@2x.png', sInfo: 'skylfx12' },
      { sName: '国家标准', sUrl: 'http://openstd.samr.gov.cn/bzgk/gb/index', sImg: '', sInfo: 'skylfx12' },
      { sName: '地方标准', sUrl: 'https://dbba.sacinfo.org.cn/stdList', sImg: '', sInfo: 'skylfx12' },
      { sName: '码云', sUrl: 'https://gitee.com/', sImg: 'https://gitee.com/static/images/logo-black.svg?t=158106664', sInfo: '账号skylfx@126.com密码16l', sLevel: 4 },
      { sName: 'github', sUrl: 'https://github.com', sImg: '', sInfo: 'skylfx@126.com s-x86' },
      { sName: '软件小宝库', sUrl: 'https://u9baoku.xyz/', sImg: '', sInfo: 'skylfx@126.com s-x86', sLevel: 4 },
    ]
  },
  {
    sitesName: '重点开源', icon: 'Guide', sites: [
      { sName: '菜鸟教程', sUrl: 'https://www.runoob.com/', sImg: '', sInfo: '', sLevel: 4 },
      { sName: 'ICON', sUrl: 'https://www.iconfont.cn/', sLevel: 4, sImg: 'https://img.alicdn.com/imgextra/i3/O1CN01Mn65HV1FfSEzR6DKv_!!6000000000514-55-tps-228-59.svg', sInfo: '新浪微博登录' },
      { sName: 'vuejs', sUrl: 'https://cn.vuejs.org/', sImg: '', sInfo: '', sLevel: 5 },
      { sName: 'elementUI', sUrl: 'https://element.eleme.io/#/zh-CN/component/installation', sImg: 'https://static.oschina.net/uploads/logo/element-ui_alsu0.png', sInfo: '', sLevel: 5 },
      { sName: 'element-plus', sUrl: 'https://element-plus.gitee.io/', sImg: '', sInfo: '', sLevel: 4 },
      { sName: 'uniapp官网', sUrl: 'https://www.dcloud.io/', sImg: '', sInfo: 'skylfx@126.com', sLevel: 4 },
      { sName: 'uviewUI', sUrl: 'https://v1.uviewui.com/', sImg: 'https://v1.uviewui.com/common/logo.png', sInfo: '', sLevel: 4 },

      { sName: 'Ant Design Vue', sUrl: 'https://vue.ant.design/docs/vue/download-cn/', sImg: '', sInfo: '', sLevel: 5 },
      { sName: 'AntV可视化', sUrl: '  https://antv.antgroup.com/', sImg: '', sInfo: '', sLevel: 4 },
      { sName: 'MyBatis-Plus', sUrl: 'https://mp.baomidou.com/guide/', sImg: '', sInfo: '' },
      { sName: 'RuoYi若依开源官网', sUrl: 'http://www.ruoyi.vip/', sImg: 'http://www.ruoyi.vip/', sInfo: '', sLevel: 5 },
      { sName: 'Jeecg-Boot开源官网', sUrl: 'http://www.jeecg.com/', sImg: 'http://www.jeecg.com/images/logo.png', sInfo: '', sLevel: 5 },
      { sName: 'JavaGuide面试', sUrl: 'https://gitee.com/SnailClimb/JavaGuide', sImg: 'https://camo.githubusercontent.com/e8c9f96658f3f7f106cf02961b9dab4ebfe8c9def9efec67561949979c7e5ae5/68747470733a2f2f6f73732e6a61766167756964652e636e2f6769746875622f6a61766167756964652f6373646e2f31633030343133633635643139393539393362663262306461663762346630332e706e67', sInfo: '' },
      { sName: 'crmeb开源商城官网', sUrl: 'https://www.crmeb.com/', sImg: 'https://www.crmeb.com/static/images/dark_logo.png', sInfo: '' },
      { sName: 'crmeb商城演示登录', sUrl: 'http://jcdt.crmeb.net/admin/login?redirect=%2Fadmin%2Fhome', sImg: '', sInfo: '' },
      { sName: 'Sa-Token授权框架', sUrl: 'https://sa-token.cc/doc.html#/', sImg: 'https://sa-token.cc/logo.png', sInfo: '' },
      { sName: 'RuoYi-Cloud-Plus微服务通用权限管理系统', sUrl: 'https://gitee.com/dromara/RuoYi-Cloud-Plus', sImg: '', sInfo: '' },
      { sName: '微信JSSDK说明文档 - 微信公众平台开发者文档', sUrl: 'http://mp.weixin.qq.com/wiki/7/aaa137b55fb2e0456bf8dd9148dd613f.html', sImg: '', sInfo: '' },
      { sName: '微信开发者平台', sUrl: 'https://mp.weixin.qq.com/cgi-bin/loginpage?t=wxm2-login&lang=zh_CN', sImg: '', sInfo: '' },
      { sName: 'BootstrapVue', sUrl: 'https://bootstrap-vue.js.org/docs/components/alert/', sImg: '', sInfo: '' },
      { sName: 'Beetl 官网', sUrl: 'http://ibeetl.com/', sImg: '', sInfo: '' },
      { sName: '搭搭云开放平台接口文档', sUrl: 'https://docs.dadayun.cn/doc/openapiDoc/index.html', sImg: '', sInfo: '' },

      { sName: '环兴商城Spring Cloud前后端分离', sUrl: 'https://gitee.com/lijiaxing_boy/huanxing-mall', sImg: '', sInfo: '' },
      { sName: 'litemall开源商城', sUrl: 'https://linlinjava.gitbook.io/litemall/', sImg: '', sInfo: '' },
      { sName: 'GitHub - FanCiyuan/macrozheng: mall项目是一套电商系统，包括前台商城系统及后台管理系统，基于SpringBoot+MyBatis实现。 前台商城系统包含首页门户、商品推荐、商品搜索、商品展示、购物车、订单流程、会员中心、客户服务、帮助中心等模块。 后台管理系统包含商品管理、订单管理、会员管理、促销管理、运营管理、内容管理、统计报表、财务管理、权限管理、设置等模块。 http://39.98.190.128/index.html', sUrl: 'https://github.com/FanCiyuan/macrozheng', sImg: '', sInfo: '' },
      { sName: 'zscat-me+uniapp+app+springcloud 商城: 基于springboot cloud构建的一个商城项目，包括前端，后端和h5应用，小程序，作为zscat应用实践的模板项目。基于SpringBoot2.x、SpringCloud和SpringCloudAlibaba并采用前后端分离的企业级微服务敏捷开发系统架构。并引入组件化的思想实现高内聚低耦合，[ 微信 + 支付宝 + 百度 + 头条 ] 小程序 + APP + 公众号 + PC + H5 项目代码简洁注释丰富上手容易，适合学习和企业中使用。真正实现了基于RBAC、jwt和oauth2的无状态统一权限认证的解决方案，面向互联网设计同时适合B端和C端用户，支持CI/CD多环境部署，积分商城，分销商城并提供应用管理方便第三方系统接入；同时还集合各种微服务治理功能和监控功能。模块包括:企业级的认证系统、开发平台、应用监控、慢sql监控、统一日志、单点登录、Redis分布式高速缓存、配置中心、分布式任务调度、接口文档、代码生成等等 - 码云 Gitee.com', sUrl: 'https://gitee.com/catshen/zscat_sw/tree/master', sImg: '', sInfo: '' },
      { sName: 'unimall 小程序 + App + 公众号H5: →→→→→部署视频教程←←←←← 又双叒叕一个B2C电商开源项目。同时支持微信小程序、H5、安卓App、苹果App。支持集群部署，单机部署。可用于B2C商城，O2O外卖，社区超市，生鲜等。 unimall使用uniapp编码。使用Java开发,SpringBoot框架、MyBatis-plus持久层框架、Redis作为缓存、MySql作为数据库。前端vuejs作为开发语言。', sUrl: 'https://gitee.com/iotechn/unimall?_from=gitee_search', sImg: '', sInfo: '' },
      { sName: 'MCMS: 完整开源！基于SpringBoot 2架构，前端基于vue、element ui。每月28定期更新版本，为开发者提供上百套免费模板,同时提供适用的插件（文章、商城、微信、论坛、会员、评论、支付、积分、工作流、任务调度等...），一套简单好用的开源系统、一整套优质的开源生态内容体系。铭飞的使命就是降低开发成本提高开发效率，提供全方位的企业级开发解决方案', sUrl: 'https://gitee.com/mingSoft/MCMS', sImg: '', sInfo: '' },
      { sName: '永久免费', sUrl: 'https://www.shishuo.com/free.htm', sImg: '', sInfo: '' },
      { sName: 'GitHub-shanghai / Octopus-Forum：使用SpringBoot，Themleaf模板引擎，OSS对象存储，SpringBoot定时任务，部署在阿里云ESC云服务器上，一个小社区。', sUrl: 'https://github.com/zykzhangyukang/Octopus-Forum', sImg: '', sInfo: '' },
      { sName: 'Spring Boot整合Mybatis-Plus和PageHelper分页插件，附项目源码_一条吃软饭的软狗-CSDN博客', sUrl: 'https://blog.csdn.net/qq_39403545/article/details/83385754', sImg: '', sInfo: '' },
      { sName: 'theodo/jeefast2.0-mybatis-plus', sUrl: 'https://gitee.com/theodo/jeefast2.0', sImg: '', sInfo: '' },
      { sName: 'GitHub - newbee-ltd/newbee-mall: newbee-mall 项目（新蜂商城）是一套电商系统，包括 newbee-mall 商城系统及 newbee-mall-admin 商城后台管理系统，基于 Spring Boot 2.X 及相关技术栈开发。 前台商城系统包含首页门户、商品分类、新品上线、首页轮播、商品推荐、商品搜索、商品展示、购物车、订单结算、订单流程、个人订单管理、会员中心、帮助中心等模块。 后台管理系统包含数据面板、轮播图管理、商品管理、订单管理、会员管理、分类管理、设置等模块。', sUrl: 'https://github.com/newbee-ltd/newbee-mall', sImg: '', sInfo: '' },
      { sName: 'ThinkItCMS: 又一个 JEE CMS,基于 Java 开发 的 cms 系统 java cms，ThinkItCMS 是一款面向模板开发，支持静态生成的CMS 系统,其支持前后端分离部署,是一款好用的 cms 系统 系统支持 默认的本地文件上传（支持断点续传）开源文件服务器fastdfs（支持断点续传） 、七牛云OSS（不支持断点续传）阿里云OSS（支持断点续传） 等第三方云存储可自由切换', sUrl: 'https://gitee.com/slfj/ThinkItCMS', sImg: '', sInfo: '' },
      { sName: '开发者手册 - 云+社区 - 腾讯云', sUrl: 'https://cloud.tencent.com/developer/section/1135832', sImg: '', sInfo: '' },
      { sName: '省钱兄淘宝客APP源码（公众号+APP+小程序+Android+IOS）电商源码: 本产品是西安省钱兄网络科技有限公司独立研发的淘宝客产品！使用uniapp技术栈！java后台技术springboot+jpa+mysql ！用户端uniapp！ 管理端vue +elementUI！承接二次订制开发，目前系统已经稳定运行一年多！目前线上运营的 的客户几百家！均可体验！我们源码不加密！支持二次开发！本公司承诺所有源码均为开源！保证保障系统稳定！ 公司介绍 ：西安省钱兄网络科技有限公司  https://www.xiansqx.com 产品介绍：https://sqx.xiansqx.com', sUrl: 'https://gitee.com/maxiaodong1996/taobaoke?_from=gitee_search', sImg: '', sInfo: '' },
      { sName: 'Apache POI - Download Release Artifacts', sUrl: 'http://poi.apache.org/download.html#POI-4.0.0', sImg: '', sInfo: '' }, { sName: '神在异乡/fileupload-demo - 码云 - 开源中国', sUrl: 'https://gitee.com/chemphern/fileupload-demo/tree/master', sImg: '', sInfo: '' },
    ]
  },
  {
    sitesName: '工具', icon: 's-tools', sites: [
      { sName: 'ISBN生成', sUrl: 'https://www.fontke.com/tool/isbn/', sImg: '', sInfo: '' },
      { sName: '鱼摆摆淘宝图片热点工具_全屏海报图片热点添加多个链接：淘宝图片热点链接在线制作工具，在线生成图片添加链接代码', sUrl: 'https://www.yubaibai.com.cn/tool/redian/', sImg: '', sInfo: '' },
      { sName: '瞭月导航 - 工程师专用导航', sUrl: 'https://www.lervor.com/nav/', sImg: '', sInfo: '' },
      { sName: '免费商用_字体_字体下载_字魂网', sUrl: 'https://izihun.com/shangyongziti/---2------/', sImg: '', sInfo: '' },
      { sName: 'ISBN条形码生成器 - 在线工具 - 字客网', sUrl: 'https://www.fontke.com/tool/isbn/', sImg: '', sInfo: '' },
      { sName: '草料二维码生成器', sUrl: 'https://cli.im/', sImg: 'https://www.lervor.com/nav/usr/uploads/2020/06/3458719850.png', sInfo: '提供二维码生成，美化，印制，管理，统计等服务' },
      { sName: '在线代码格式化', sUrl: 'https://tool.oschina.net/codeformat/html', sImg: '', sInfo: '提供格式化HTML、XML、CSS、JSON、JS、Java、SQL' },
      { sName: '在线PS', sUrl: 'https://www.uupoop.com/', sImg: 'https://www.uupoop.com/favicon.ico', sInfo: '一个专业精简的在线ps图片照片制作处理软件工具' },
      { sName: '在线加密解密', sUrl: 'https://tool.oschina.net/encrypt', sImg: '', sInfo: '提供加密/解密、散列/哈希、BASE64、图片/BASE64转换' },
      { sName: '编码转换', sUrl: 'https://tool.chinaz.com/tools/unicode.aspx', sImg: 'https://www.lervor.com/nav/usr/uploads/2020/06/70526281.png', sInfo: 'Unicode编码转换,Unicode转ASCII,ASCII转Unicode,中文转Unicode,Unicode转中文' },
      { sName: '英文字母大小写转换', sUrl: 'https://www.iamwawa.cn/daxiaoxie.html', sImg: 'https://www.iamwawa.cn/Public/img/favicon.png', sInfo: '在线英文字母大小写转换' },
      { sName: '短链接网址缩短服务', sUrl: 'http://check.uomg.com/urlcn_dwz.html', sImg: 'http://check.uomg.com/favicon.png', sInfo: '在线短链接网址缩短服务' },
      { sName: 'TinyPNG', sUrl: 'https://tinypng.com/', sImg: 'https://tinypng.com/images/favicon.ico', sInfo: '易用的图片在线压缩工具' },
      { sName: 'Iconfont', sUrl: 'https://www.iconfont.cn/', sImg: 'https://img.alicdn.com/tps/i4/TB1_oz6GVXXXXaFXpXXJDFnIXXX-64-64.ico', sInfo: '阿里巴巴矢量图标库' },
      { sName: 'Font Awesome 中文网', sUrl: 'http://www.fontawesome.com.cn/icons-ui/', sImg: 'https://www.lervor.com/nav/usr/uploads/2020/06/761812384.png', sInfo: '一款基于css框架的网页字体图标库，它完全免费' },
      { sName: 'Iconfinder', sUrl: 'https://www.iconfinder.com/', sImg: 'https://www.lervor.com/nav/usr/uploads/2020/06/671849227.png', sInfo: '4,400,000+ free and premium vector icons in SVG, PNG, CSH and AI format' },
      { sName: 'Feather', sUrl: 'https://feathericons.com/', sImg: 'https://feathericons.com/favicon-32x32.png', sInfo: 'Simply beautiful open source icons' },
      { sName: 'FontEditor', sUrl: 'http://fontstore.baidu.com/static/editor/index.html', sImg: 'https://www.baidu.com/favicon.ico', sInfo: '百度字体编辑器' },
      { sName: '标智客', sUrl: 'https://www.logomaker.com.cn/', sImg: 'https://www.logomaker.com.cn/favicon.ico', sInfo: 'logo在线制作、标志设计、公司logo设计' },
      { sName: '花瓣', sUrl: 'https://huaban.com/', sImg: 'https://huaban.com/img/touch-icon-iphone.png', sInfo: '创意灵感天堂，搜索、发现设计灵感、设计素材' },
      { sName: '全景视觉', sUrl: 'https://www.quanjing.com/', sImg: 'https://www.quanjing.com/favicon.ico', sInfo: '提供图片素材，图片搜索，图片分享，高清图片下载' },
      { sName: 'Pexels', sUrl: 'https://www.pexels.com/zh-cn/', sImg: 'https://www.pexels.com/favicon.ico', sInfo: '免费素材照片，可以在任何地方使用。✓ 免费用于商业用途 ✓ 无需注明归属' },
      { sName: 'UI中国用户体验设计平台', sUrl: 'https://www.ui.cn/', sImg: 'https://www.ui.cn/Public/img/favicon.ico', sInfo: '图形交互与界面设计交流、作品展示、学习平台。' },
      { sName: '标智客', sUrl: 'https://www.logomaker.com.cn/', sImg: 'https://www.logomaker.com.cn/favicon.ico', sInfo: 'logo在线制作、标志设计、公司logo设计' },
      { sName: 'GitMind', sUrl: 'https://gitmind.cn', sImg: 'https://qncdnimg.aoscdn.com/local/gitmind.cn/img/favicon.png', sInfo: 'GitMind是一款免费在线思维导图流程图软件，支持Windows/Mac/Linux多平台操作及内容同步' },
      { sName: 'ProcessOn', sUrl: 'https://www.processon.com', sImg: 'https://www.processon.com/favicon.ico', sInfo: '免费在线作图，思维导图，流程图，实时协作' },
      { sName: '百度脑图', sUrl: 'https://naotu.baidu.com/', sImg: 'https://naotu.baidu.com/favicon.ico', sInfo: '便捷的脑图编辑工具。控制创意，如此简单' },
      { sName: '墨刀', sUrl: 'https://modao.cc/', sImg: 'https://modao.cc/favicon.ico', sInfo: '一款专业、可靠、简洁、易懂的在线产品原型工具与产品设计团队协作平台' },
      { sName: '摹客', sUrl: 'https://www.mockplus.cn', sImg: 'https://www.mockplus.cn/favicon.ico', sInfo: '集设计协作平台、原型设计和设计规范为一体' },
      { sName: '即时原型(xiaopiu)', sUrl: 'https://www.xiaopiu.com', sImg: 'https://img.xiaopiu.com/favicon.ico', sInfo: '产品原型设计工具与团队实时协作平台' },
      { sName: '蓝湖', sUrl: 'https://lanhuapp.com/', sImg: 'https://img.sobot.com/console/d5a36b5051fa44aab20895f49e7906a5/userImage/20191127175640784.PNG', sInfo: '高效的产品设计协作平台' },
      { sName: '语雀', sUrl: 'https://www.yuque.com', sImg: 'https://gw.alipayobjects.com/zos/rmsportal/UTjFYEzMSYVwzxIGVhMu.png', sInfo: '优雅高效的在线文档编辑与协同工具' },
      { sName: '飞书', sUrl: 'https://www.feishu.cn/', sImg: 'https://p6-hera.byteimg.com/tos-cn-i-jbbdkfciu3/f3de430ed2b64f90a95fb8a393dfa6bd~tplv-jbbdkfciu3-image:0:0.image', sInfo: '集视频会议、在线文档、移动办公、协同软件的一站式企业沟通协作平台' },
      { sName: '极客学院', sUrl: 'https://www.jikexueyuan.com/', sImg: 'https://www.jikexueyuan.com/favicon.ico', sInfo: 'IT职业在线教育平台,拥有海量高清IT职业课程,涵盖30+个技术领域' },
      { sName: '中国大学MOOC(慕课)', sUrl: 'https://www.icourse163.org/', sImg: 'https://edu-image.nosdn.127.net/32a8dd2a-b9aa-4ec9-abd5-66cd8751befb.png', sInfo: '国家精品课程在线学习平台' },
      { sName: '网易云课堂', sUrl: 'https://study.163.com/', sImg: 'https://study.163.com/favicon.ico', sInfo: '一个专注职业技能提升的在线学习平台' },
      { sName: '优设网', sUrl: 'https://www.uisdc.com/', sImg: 'https://image.uisdc.com/wp-content/uploads/2018/05/uisdc-ico-apple.jpg', sInfo: '设计师交流学习平台' },
      { sName: '华为云', sUrl: 'https://www.huaweicloud.com/', sImg: '', sInfo: '提供云服务器,云数据库,云存储,CDN,大数据,云安全等公有云产品' },
      { sName: '阿里云', sUrl: 'https://www.aliyun.com/', sImg: 'https://img.alicdn.com/tfs/TB1qNVdXlGw3KVjSZFDXXXWEpXa-620-620.png', sInfo: '提供云服务器、云数据库、云存储、CDN、大数据等服务' },
      { sName: '腾讯云', sUrl: 'https://cloud.tencent.com/', sImg: 'https://cloud.tencent.com/favicon.ico?t=201902181234', sInfo: '云服务器、云数据库、云存储、视频与CDN、域名注册' },
      { sName: '又拍云', sUrl: 'https://www.upyun.com/', sImg: 'https://www.upyun.com/static/favicon-64x64.png', sInfo: 'CDN,云分发,云存储,SSL证书服务,HTTPS,短视频SDK,直播SDK,云服务' },
      { sName: '七牛云', sUrl: 'https://www.qiniu.com/', sImg: 'https://www.qiniu.com/favicon.ico', sInfo: '对象存储、CDN加速、直播云、容器云、大数据、深度学习平台' }
    ]
  },
  {
    sitesName: '业务', icon: 'Lightning', sites: [
      { sName: '闻声谷', sUrl: 'http://www.w-ji.com/?tdsourcetag=s_pctim_aiomsg', sImg: '', sInfo: '' },
      { sName: '上海阳光医药采购网', sUrl: 'http://www.yyzbsw.sh.cn/xxgk/gggs/2019/06/11/8828.shtml', sImg: '', sInfo: '' },
      { sName: '重磅：民营医院、医保药店全线接入省级平台采购_行业动态_药智新闻', sUrl: 'https://news.yaozh.com/archive/26262.html', sImg: '', sInfo: '' },
      { sName: '远方软件-V6招投标管理-全业务', sUrl: 'http://www.youngfriend.com.cn/v6solution/bid.html', sImg: '', sInfo: '' },
      { sName: '易采购—让招标采购管理更容易', sUrl: 'http://www.dianzicaigou.com.cn/products/index.html', sImg: '', sInfo: '' },
      { sName: '康拓普-天诚电子招投标系统-政企专用电子招投标平台-', sUrl: 'http://www.szcomtop.com/bid/', sImg: '', sInfo: '' },
      { sName: '北京优易惠技术有限公司——招标网_招投标_招标公告_招标信息网', sUrl: 'http://www.uehchina.com/', sImg: '', sInfo: '' },
      { sName: '山东能源集团电子招标投标交易平台项目招标公告-山东能源集团', sUrl: 'http://www.snjt.com/info/1143/74410.htm', sImg: '', sInfo: '' },
      { sName: '明信阳光采购管理平台_招投标系统,招投标软件,电子招标投标系统,电子招投标软件', sUrl: 'http://www.4008887378.com/zhaotoubiaoxitong.html', sImg: '', sInfo: '' },
      { sName: '易招标', sUrl: 'http://www.ebidding.com.cn/', sImg: '', sInfo: '' },
      { sName: '中国招标投标公共服务平台', sUrl: 'http://www.cebpubservice.com/', sImg: '', sInfo: '' },
      { sName: '小蜜蜂仓储', sUrl: 'http://www.smartwms.cn/h-col-133.html', sImg: '', sInfo: '' },
      { sName: '8Manage采购管理平台移动APP', sUrl: 'http://www.8manage.cn/supplier/spm_app.html', sImg: '', sInfo: '' },
      { sName: '甄云供应商管理系统_360度洞悉供应商全生命周期', sUrl: 'https://www.going-link.com/supplier', sImg: '', sInfo: '' },
      { sName: '供采易-企业供应链B2B交易平台', sUrl: 'http://www.xsaas.com/', sImg: '', sInfo: '' },
      { sName: '中铁二十四局集团有限公司物资集采平台', sUrl: 'https://cr24b.go.1688.com/page/purchase.htm?spm=0.0.0.0.BdEDnD0', sImg: '', sInfo: '' },
      { sName: '必联网-在线电子招投标与互联网采购供应交易平台_招标_采购_SAAS平台', sUrl: 'http://www.ebnew.com/', sImg: '', sInfo: '' },
      { sName: '中国铁路上海局集团有限公司物资采购商务平台', sUrl: 'http://www.e-shrailway.com/index.jsp', sImg: '', sInfo: '' },
      { sName: '中国铁路95306网 铁路物资采购与招商平台', sUrl: 'http://wzcgzs.95306.cn/mainPage.do', sImg: '', sInfo: '' },
      { sName: '云企采电子采购平台 http://www.yunqicai.cn', sUrl: 'https://gitee.com/lgl8711/tpb', sImg: '', sInfo: '' },
      { sName: '云呐资产物联服务平台--登录', sUrl: 'https://www.easyitom.com/ServiceProvider/login.jsp', sImg: '', sInfo: '' },
      { sName: '首页-维佳供应链第三方仓储外包供应商', sUrl: 'http://www.iweja.com/index.html', sImg: '', sInfo: '' },
      { sName: '操作手册-帮助中心-柠檬云进销存', sUrl: 'https://help1.ningmengyun.com/#/jxc/HandleForJXC?subMenuId=9', sImg: '', sInfo: '' },
      { sName: '京东物流教育', sUrl: 'https://xuexizhongxin.wuliujie.com/', sImg: '', sInfo: '' },
      { sName: '网店管家云端版_电子商务ERP/CRM/OA解决方案_网店管家官方网站', sUrl: 'http://www.es86.com/product-wdgjcloud.html', sImg: '', sInfo: '' },
      { sName: '契约锁电子合同-电子签约和实体印章管控的一体化服务平台！', sUrl: 'https://www.qiyuesuo.com/case/bkg/jinju.html', sImg: '', sInfo: '' },
    ]
  },
  {
    sitesName: '生活', icon: 's-grid', sites: [
      { sName: '学习强国', sUrl: 'https://www.xuexi.cn/', sImg: '', sInfo: '' },
      { sName: '凤凰知音', sUrl: 'https://ffp.airchina.com.cn/app/product/detail?id=5625&pid=grzx:dnxh:01:03:5625', sImg: '', sInfo: '' },
      { sName: '中国计算机技术职业资格网', sUrl: 'https://bm.ruankao.org.cn/', sImg: '', sInfo: '' },
    ]
  }
]